### ISSUE TITLE
Vaillant controls are not visible in Home app

### ISSUE THREAD

**Issue by urosbe** [lmelon/homebridge-vaillant-vrc9xx#3]
After installing this plugin to my existing Homebridge setup, everything looked ok in the logs, except that I get the following warning when starting homebridge:

> Ignoring VaillantVRC9xx Platform setup becase it is not configured

I am using VR900 module, connected to my FlexoCompact heating system.

My config file looks like that (I have masked username and password with *):
> 		{
> 		  "platform": "VaillantVRC9xx",
> 		  "api": {
> 					"polling": 60,
> 					"user": {
> 						"name": "*******",
> 						"password": "*******",
> 						"device": "1234-56789-1011"
> 					}
> 				}
> 		}

But from additional log it looks like plugin connects to Vaillant API without a problem:
![v1](https://user-images.githubusercontent.com/7140012/68948637-98f82e80-07b8-11ea-9427-45d80ea5863b.png)

![v2](https://user-images.githubusercontent.com/7140012/68948640-9a295b80-07b8-11ea-8d01-31e20c593440.png)

![v3](https://user-images.githubusercontent.com/7140012/68948643-9b5a8880-07b8-11ea-9338-7757f30cfd44.png)

![v4](https://user-images.githubusercontent.com/7140012/68948650-9e557900-07b8-11ea-96bd-4f39b621383d.png)

The only problem is that I do not see any new controlls/accessories in Home app on my iPhone. I have also tried to add them manually with Homebridge code, but there are no new accessories listed. I have also tried in Eve app, but it's the same. Only existing accessories appears in the list.

I look forward for any advice.

**Comment by lmelon** [comment]
The first error message you can ignore ... there is somehow a duplicate definition of the plugin ... I don't know how to get rid of it but I do have the same.

From what I see in the log the plugin is working correctly. So it is purely between homebridge and the Home App.

Did you correctly scanned the QR code visible in the log when Homebridge starts ? Or did you capture the code "031-45-154" ?

Do you have other accessories in the same homebridge install ? are they showing up in Home App ?

**Comment by urosbe** [comment]
I have other accessories connected to this Homebridge installation (7 IP cameras and Marantz AVR with 2 zones) and all other accessories works ok. Marantz is defined as accessory, so it automatically appeared in Home app, but I had to add cameras manually which are defined as platform. 

Manually procedure that I have used was + sign at upper right corner -> Add Accessory -> I Don't Have a Code or Cannot Scan -> Manual Code - Enter code and then I entered 031 45 154. List with new devices (cameras) appeared and I was able to add them to the list.

**Comment by lmelon** [comment]
Sorry I overlooked one of your screenshot ... 
You seems to have two heating zone (TALNO & KONVEKTOR), is it correct ?
This is something that I don't have in my setup. 

There is apparently an issue to locate the current temperature:

> KONVEKTOR > Updating Current Temperature (from/to) : undefined undefined

Other characteristics are ok.
I'll investigate on my side if I see something obvious in this scenario. But it would help to be able to reproduce. Would you grant me access to your installation for just a few hours ?

**Comment by urosbe** [comment]
I have two zones in installation, but only first one (TALNO) is active. Second zone (KONVEKTOR) is only preset in case I will use system for cooling during the hot summer days. For now I only have installation pipes and preset zone, but did not even bought convetors yet. Installer guy preset everything just in case, so it is ready if there will be need for cooling.

I can grant you access - the easiest way would probably be that I add you as new user in Vaillant iOS mobile app. I only have to enter your e-mail to invite you.

**Comment by lmelon** [comment]
Please pm me on Twitter @lmelon so that we can setup this in private.

**Comment by lmelon** [comment]
After investigation, this issue was not related to the plugin. 
If anyone encounter the same problem, two possible options:

1) Remove the homebridge install from HomeKit than re-add it again

This approach might be annoying if you have a lot of accessories linked to this installation as you will lose all you setup (name, room allocation, automations, ...)

2) Install a dedicated instance of homebridge for the plugin

If you do so, don't forget to change the username parameter.
If you install multiple instances on the same server, then have to be on different port number

>```json
>    "bridge": {
>        "name": "Homebridge",
>       "username": "CC:DD:EE:FF:00:11",
>        "port": 51826,
>        "pin": "123-45-678"
>    },
>```
