### ISSUE TITLE
After update the homebridge stopps and shows {"errorCode":"NO_ROOMS_AVAILABLE"}

### ISSUE THREAD

**Issue by tedtedted77** [lmelon/homebridge-vaillant-vrc9xx#5]
Hi,

after updating with the newest version my homebridge stopped an showed the following:

Jan 08 12:35:13 raspberrypi homebridge[10090]: [2020-1-8 12:35:13] [VaillantVRC9xx] [Get facilities]
Jan 08 12:35:13 raspberrypi homebridge[10090]: [2020-1-8 12:35:13] [VaillantVRC9xx] [Get facility details]
Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] [Get facility live report]
Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] [Get facility status]
Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] [Get facility gateway information]
Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] [Get facility room-by-room information]
**Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] 409 - Conflict - {"errorCode":"NO_ROOMS_AVAILABLE"}
Jan 08 12:35:14 raspberrypi homebridge[10090]: [2020-1-8 12:35:14] [VaillantVRC9xx] Error while refreshing facility Zuhause  -- 21183900202529220938027166N4**

I have the Vaillant VRC900 Module an no rooms configured and no need to do this. The hombridge plugin worked really fine, till this update.
I'm a beginner in programming and was very lucky to get the Homebridge work. What can I do?

Kind regards

**Comment by lmelon** [comment]
Well, sorry about that. Until I figure out what the problem is, you can always reinstall the previous version by doing "npm i homebridge-vaillant-vrc9xx@0.4.2".

Your system is apparently reporting "room-by-room" (Ambisense) feature ... while apparently none is configured.

VR900 should not be reporting this feature as it doesn't have it. My VR900 is definitely not doing it. Do you you have anything else in your system ?

**Comment by lmelon** [comment]
I just release a preview version with 2 features:
1/ you can disable the ambiSENSE function even if it is reported by the system (disabled: true in the "rooms" section)
2/ you can activate a "debug" function that will dump in a file the result of querying Vaillant API 

documentation is here: https://www.npmjs.com/package/homebridge-vaillant-vrc9xx/v/0.5.1-RC.1

to install just do: "npm install homebridge-vaillant-vrc9xx@next"

could you please install it (with the appropriate config to disable ambiSENSE) and tell me how it goes ?
could you also activate debug, run it and post the dump file here ? do not forget to remove debug afterwards.

**Comment by tedtedted77** [comment]
Thanks for the perfect support. 
Usually I installed homebridge plugins with homebridge-config-ui-x. I tried with the command line but got this result:

Jan 09 09:45:10 raspberrypi homebridge[2568]: [2020-1-9 9:45:10] Error: The requested platform 'VaillantVRC9xx' was not registered by any plugin.
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Module._compile (internal/modules/cjs/loader.js:959:30)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Module.load (internal/modules/cjs/loader.js:815:32)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
Jan 09 09:45:10 raspberrypi homebridge[2568]:     at internal/main/run_main_module.js:17:11

I think something went wrong within the installation. I think I'll wait until the new version could installed with config-ui-x.

**Comment by lmelon** [comment]
Version 0.5.1 has been released. Let me know if activating the "disabled" parameter in the config does improve the situation.

**Comment by tedtedted77** [comment]
Bingo! Situation improved. Thanks for your support and this great plugin!
