### ISSUE TITLE
Login unsuccessful

### ISSUE THREAD

**Issue by GusMuche** [lmelon/homebridge-vaillant-vrc9xx#7]
Hi,

Since a few days I've trying to get this plugin working on my installation.

I've create a dedicated user for this use an get this error :
```
[VaillantVRC9xx] Finished launching
[VaillantVRC9xx] 401 - Unauthorized - {"errorCode":"NOT_AUTHORIZED"}
[VaillantVRC9xx] Failed to get facilities list ... will retry in 30 seconds
```

Do I need to activate something with this account ? I've read that a developer account is needed to work with the API of Vaillan. Is it the case ?

Thanks in advance for your return,

Gus

**Comment by lmelon** [comment]
Could you try the following:

- use your current user in the config file of the plugin
- try and connect via the app with this newly created user
- any other error message in the log ? 
- could you publish your config for the plugin (replacing every characters except the first and last one of username & password by '*' (without the quotes :) )

**Comment by lmelon** [comment]
> Do I need to activate something with this account ? I've read that a developer account is needed to work with the API of Vaillan. Is it the case ?

No and no. If you see the newly created user in the app as having access to your installation ... that should be fine.

**Comment by GusMuche** [comment]
First, thanks for your reply

What I've try :
- Try with current user : KO (=same issue)
- Try new user on the app : OK

My last log :

```
[VaillantVRC9xx] Initializing VaillantVRC9xx platform...
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] VaillantVRC9xx Platform loaded - version 0.5.1
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Dumping queries to path /homebridge
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Received callback
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Start polling for data
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Starting poller ...
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Refreshing list of facilities
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] Get all facilities ...
[4/25/2020, 7:24:08 PM] [VaillantVRC9xx] [Login]
[4/25/2020, 7:24:09 PM] [VaillantVRC9xx] Finished launching
[4/25/2020, 7:24:09 PM] [VaillantVRC9xx] 401 - Unauthorized - {"errorCode":"NOT_AUTHORIZED"}
[4/25/2020, 7:24:09 PM] [VaillantVRC9xx] Failed to get facilities list ... will retry in 30 seconds
```

and my config :

```
{
      "platform": "VaillantVRC9xx",
            "api": {
                "debug": true,
                "polling": 60,
                "user": {
                    "name": "myEmail",
                    "password": "myPass",
                    "device": "1234-56789-1011"
                },
                "rooms": {
                    "disabled": false,
                    "veto_duration": 180
                }
            }
        }
```

Any idea ?

**Comment by lmelon** [comment]
The « name » parameter should not be the email address but the username you defined when registering on vaillant app / web site

**Comment by GusMuche** [comment]
Curious... I didn't give a name for my users on the app.

I use the eRelax/VSmart app on iOS. If I want to create a user I just have to write an email address and a password.

Then I search on the web for web interface and the only that I found was the [mobilDIALOG 2.0](https://www.vaillant.at/privatanwender/produkte/mobile-apps/mobildialog-2-0/). Seems that is not use in all country.

I can't login on this page with my two accounts.

What kind of website do you use with your accounts ?

**Comment by lmelon** [comment]
Sorry but eRelax is a totally different system. This plugin is only designed to work with a VR900 or VR920 device and the so-called MultiMATIC app

**Comment by GusMuche** [comment]
Hooowwww so disappoint for me.

Sorry for the unnecessary issue and thanks for your replies.

**Comment by discofris** [comment]
Had the same issue. Also using hte eRelax/vSmart iOS app.
Maybe put it in the requirements somewhere?

**Comment by lmelon** [comment]
Happy to give it a look. But I don't own this system. So I would need some to give me access to his/her system so that I can see what is possible.

**Comment by discofris** [comment]
Would like to give you access, but unfortunately I cannot create a read-only account.
How can we create some kind of trust between us?
